INSERT INTO USER (ID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD) VALUES(1, 'Kader', 'Çelik', 'kadercelikk34@gmail.com','$2a$10$o3oNkdSBE8F0M.k/BJUalOF1vJQNmq1dppXklaC165uM6TqU/ieZm');
INSERT INTO USER (ID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD) VALUES(2, 'John', 'Doe', 'john@doe.com','$2a$10$70Szc4hs3KzfyqipvE9eCugUWYawW1C8yF6hbb2E7R0m.KFjDhN6m');

INSERT INTO INVOICES (ID,AMOUNT,PRODUCT_NAME, BILLING_NO,INVOICE_STATUS,USER_ID) VALUES(1, 30, 'Usb Disc', 'TR00','APPROVED',1);
INSERT INTO INVOICES (ID,AMOUNT,PRODUCT_NAME, BILLING_NO,INVOICE_STATUS,USER_ID) VALUES(2, 40, 'Hard Disc', 'TR01','APPROVED',1);
INSERT INTO INVOICES (ID,AMOUNT,PRODUCT_NAME, BILLING_NO,INVOICE_STATUS,USER_ID) VALUES(3, 10, 'Webcam', 'TR02','NOT_APPROWED',1);

INSERT INTO INVOICES (ID,AMOUNT,PRODUCT_NAME, BILLING_NO,INVOICE_STATUS,USER_ID) VALUES(4, 50, 'Usb Disc', 'TR00','APPROVED',2);
INSERT INTO INVOICES (ID,AMOUNT,PRODUCT_NAME, BILLING_NO,INVOICE_STATUS,USER_ID) VALUES(5, 60, 'Head Phone Sony', 'TR01','APPROVED',2);
INSERT INTO INVOICES (ID,AMOUNT,PRODUCT_NAME, BILLING_NO,INVOICE_STATUS,USER_ID) VALUES(6, 30, 'San Disc', 'TR02','NOT_APPROWED',2);